if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/buffer_pool_manager_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/buffer_pool_manager_test[1]_tests.cmake")
else()
  add_test(buffer_pool_manager_test_NOT_BUILT buffer_pool_manager_test_NOT_BUILT)
endif()
