if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/crash_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/crash_test[1]_tests.cmake")
else()
  add_test(crash_test_NOT_BUILT crash_test_NOT_BUILT)
endif()
