if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/disk_manager_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/disk_manager_test[1]_tests.cmake")
else()
  add_test(disk_manager_test_NOT_BUILT disk_manager_test_NOT_BUILT)
endif()
