if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hash_table_page_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hash_table_page_test[1]_tests.cmake")
else()
  add_test(hash_table_page_test_NOT_BUILT hash_table_page_test_NOT_BUILT)
endif()
