if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hyperloglog_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hyperloglog_test[1]_tests.cmake")
else()
  add_test(hyperloglog_test_NOT_BUILT hyperloglog_test_NOT_BUILT)
endif()
