if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/lru_replacer_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/lru_replacer_test[1]_tests.cmake")
else()
  add_test(lru_replacer_test_NOT_BUILT lru_replacer_test_NOT_BUILT)
endif()
