if(EXISTS "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/orset_test[1]_tests.cmake")
  include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/orset_test[1]_tests.cmake")
else()
  add_test(orset_test_NOT_BUILT orset_test_NOT_BUILT)
endif()
