# CMake generated Testfile for 
# Source directory: C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test
# Build directory: C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/crash_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/binder_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/arc_replacer_performance_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/arc_replacer_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/buffer_pool_manager_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/clock_replacer_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/lru_k_replacer_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/lru_replacer_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/rwlatch_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/extendible_htable_concurrent_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/extendible_htable_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hash_table_page_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hash_table_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/count_min_sketch_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/hyperloglog_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/orset_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/skiplist_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/trie_debug_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/trie_noncopy_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/trie_store_noncopy_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/trie_store_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/trie_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/b_plus_tree_concurrent_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/b_plus_tree_delete_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/b_plus_tree_insert_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/b_plus_tree_sequential_scale_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/b_plus_tree_tombstone_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/disk_manager_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/disk_scheduler_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/extendible_htable_page_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/page_guard_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/tmp_tuple_page_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/tuple_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/txn_abort_serializable_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/txn_executor_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/txn_index_concurrent_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/txn_index_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/txn_scan_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/txn_timestamp_test[1]_include.cmake")
include("C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/test/type_test[1]_include.cmake")
add_test(SQLLogicTest.p0.01-lower-upper "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p0.01-lower-upper.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p0.01-lower-upper PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p0.02-function-error "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p0.02-function-error.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p0.02-function-error PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p0.03-string-scan "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p0.03-string-scan.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p0.03-string-scan PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.01-seqscan "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.01-seqscan.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.01-seqscan PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.02-insert "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.02-insert.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.02-insert PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.03-update "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.03-update.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.03-update PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.04-delete "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.04-delete.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.04-delete PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.05-index-scan-btree "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.05-index-scan-btree.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.05-index-scan-btree PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.06-empty-table "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.06-empty-table.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.06-empty-table PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.07-simple-agg "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.07-simple-agg.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.07-simple-agg PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.08-group-agg-1 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.08-group-agg-1.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.08-group-agg-1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.09-group-agg-2 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.09-group-agg-2.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.09-group-agg-2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.10-simple-join "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.10-simple-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.10-simple-join PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.11-multi-way-join "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.11-multi-way-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.11-multi-way-join PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.12-repeat-execute "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.12-repeat-execute.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.12-repeat-execute PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.13-nested-index-join "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.13-nested-index-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.13-nested-index-join PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.14-hash-join "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.14-hash-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.14-hash-join PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.15-multi-way-hash-join "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.15-multi-way-hash-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.15-multi-way-hash-join PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.16-sort-limit "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.16-sort-limit.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.16-sort-limit PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.17-topn "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.17-topn.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.17-topn PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.18-integration-1 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.18-integration-1.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.18-integration-1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.19-integration-2 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.19-integration-2.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.19-integration-2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.20-window-function "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.20-window-function.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.20-window-function PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.leaderboard-q1 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.leaderboard-q1.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.leaderboard-q1 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.leaderboard-q2 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.leaderboard-q2.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.leaderboard-q2 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.leaderboard-q3 "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/build-win/bin/bustub-sqllogictest" "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/sql/p3.leaderboard-q3.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.leaderboard-q3 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;90;add_test;C:/Users/zeyu6/Desktop/Database/Projects/C++ Primer/bustub/test/CMakeLists.txt;0;")
